import type { NextPage } from 'next';
import Head from 'next/head';
import HdmiInput from '../components/HdmiInput';
import OffButton from '../components/OffButton';
import { stDemianaPorts, stJohnPorts } from '../utils/ports';

const Home: NextPage = () => {
	const stDemianaInputs = stDemianaPorts.filter(
		(port) => port.mode === 'input' && port.name
	);
	const stJohnInputs = stJohnPorts.filter(
		(port) => port.mode === 'input' && port.name
	);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='container mx-auto max-w-md space-y-12 p-4'>
				<h1 className='text-center text-3xl'>SDSA HDMI System</h1>
				<section className='space-y-6'>
					<h2 className='text-2xl'>Arabic Church</h2>
					<OffButton building='demiana' />

					<div className='grid grid-cols-3 gap-4'>
						{stDemianaInputs.map((port) => (
							<HdmiInput key={port.number} port={port} building='demiana' />
						))}
					</div>
				</section>

				<section className='space-y-6'>
					<h2 className='text-2xl'>English Church</h2>
					<OffButton building='john' />

					<div className='grid grid-cols-3 gap-4'>
						{stJohnInputs.map((port) => (
							<HdmiInput key={port.number} port={port} building='john' />
						))}
					</div>
				</section>
			</main>
		</>
	);
};

export default Home;
